.TH Monitorování DHCP komunikace
.SH NAME
FIT VUT - ISA Projekt 2023 - Monitorování DHCP komunikace
.SH SYNOPSIS
.B dhcp-stats
[\fIoptions\fR]
.SH DESCRIPTION
.B dhcp-stats
je program urceny ku generovaniu statistiky vytazenia sietoveho prefixu, zadaneho v prikazovej riadke, v DHCP komunikacii. Aplikacia generuje statistiku zo vstupneho suboru alebo zo sietoveho rozhrania do okna aplikacie.
Hodnoty vytazenia prefixov sa aktualizuju v okne automaticky.
Pri prekroceni 50% vytazenia zadaneho IP prefixu dojde k zapisu tejto hlasky do syslogu a do okna programu.
.SH OPTIONS
.TP
.BR \-r " <file-name.pcap>
Meno analyzovaneho .pcap suboru v aktualnom adresari.
Je pozadovane pouzit parameter -r alebo -i.
.TP
.BR \-i " <interface-name>
Nazov sietoveho rozhrania na ktorom bude prebiehat monitorovanie DHCP komunikacie.
Je pozadovane pouzit parameter -r alebo -i.
.TP
.BR " <IP/prefix>
Obsahuje vsetky pozadovane analyzovane IP adresy vratane prefixu.
Zapisujte v tvare "IP/prefix".
Jednotlive IP adresy musia byt oddelene medzerami.

